---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      timezone: 06:00 UTC
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
      timezone: 06:00 UTC
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
      timezone: 06:00 UTC
    commit-message:
      prefix: chore
      include: scope
