---
name: Linting

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  hadolint:
    name: hadolint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run hadolint
        uses: reviewdog/action-hadolint@v1

  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: reviewdog/action-golangci-lint@v1

  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run yamllint
        uses: reviewdog/action-yamllint@v1
